services:
  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: a_very_secure_password

  #adminer:
    #image: adminer
    #restart: always
    #ports:
    #  - 8080:8080
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on: 
      - db
    ports:
      - "8000:8000"